use crossterm::event::{KeyCode, KeyEvent, KeyModifiers};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Action {
    Quit,
    Save,
    Undo,
    Redo,
    ToggleSidebar,
    ToggleBottomPanel,
    FocusTerminal,
    FocusClaudeLog,
    NextTab,
    CycleBottomTab,
    FocusSidebar,
    ShowCheatsheet,
    Escape,
    InsertChar(char),
    InsertTab,
    Backspace,
    Delete,
    Enter,
    CursorUp,
    CursorDown,
    CursorLeft,
    CursorRight,
    WordLeft,
    WordRight,
    Home,
    End,
    PageUp,
    PageDown,
    SelectAll,
    Noop,
}

pub fn map_key(key: KeyEvent) -> Action {
    let ctrl = key.modifiers.contains(KeyModifiers::CONTROL);
    let shift = key.modifiers.contains(KeyModifiers::SHIFT);

    match key.code {
        KeyCode::Char('q') if ctrl => Action::Quit,
        KeyCode::Char('s') if ctrl => Action::Save,
        KeyCode::Char('z') if ctrl => Action::Undo,
        KeyCode::Char('y') if ctrl => Action::Redo,
        KeyCode::Char('a') if ctrl => Action::SelectAll,
        KeyCode::Char('b') if ctrl => Action::ToggleSidebar,
        KeyCode::Char('`') if ctrl => Action::ToggleBottomPanel,
        KeyCode::Char('j') if ctrl => Action::FocusTerminal,
        KeyCode::Char('l') if ctrl => Action::FocusClaudeLog,
        KeyCode::Char('e') if ctrl => Action::FocusSidebar,
        KeyCode::Char('?') if ctrl => Action::ShowCheatsheet,
        KeyCode::Char('/') if ctrl && shift => Action::ShowCheatsheet,
        KeyCode::F(1) => Action::ShowCheatsheet,
        KeyCode::BackTab if ctrl => Action::NextTab,
        KeyCode::Tab if ctrl => Action::NextTab,
        KeyCode::Tab => Action::InsertTab,
        KeyCode::Esc => Action::Escape,
        KeyCode::Left if ctrl => Action::WordLeft,
        KeyCode::Right if ctrl => Action::WordRight,
        KeyCode::Char(c) if !ctrl => Action::InsertChar(c),
        KeyCode::Backspace => Action::Backspace,
        KeyCode::Delete => Action::Delete,
        KeyCode::Enter => Action::Enter,
        KeyCode::Up => Action::CursorUp,
        KeyCode::Down => Action::CursorDown,
        KeyCode::Left => Action::CursorLeft,
        KeyCode::Right => Action::CursorRight,
        KeyCode::Home => Action::Home,
        KeyCode::End => Action::End,
        KeyCode::PageUp => Action::PageUp,
        KeyCode::PageDown => Action::PageDown,
        _ => Action::Noop,
    }
}
